[package]
name = "rust_testing_example"
version = "0.1.0"
authors = ["Tom Dymel <td@wps.de>"]
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.9.5"
csv = "1.1"
mutagen = { git="https://github.com/llogiq/mutagen" }